apiVersion: apps/v1
kind: Deployment

metadata:
  name: wandernest-deployment
  namespace: wandernest

spec:
  replicas: 2

  selector:
    matchLabels:
      app: wandernest

  template:
    metadata:
      labels:
        app: wandernest

    spec:
      containers:
      - name: wandernest-container
        image: 747582940940.dkr.ecr.ap-south-1.amazonaws.com/wandernest:latest
        ports:
        - containerPort: 80
